### ISSUE TITLE
SBTC not showing up on OKX wallet.

### ISSUE THREAD

**Issue by Ghost-hand** [babylonchain/covenant-emulator#21]
Somehow after trying to get the OKX wallet to show the SBTC custom chain, it hasn't worked, ran it on multiple browsers. if there is any way to solve this problem, it would be greatly appreciated.

![image](https://github.com/babylonchain/covenant-emulator/assets/155332041/5fd3ce32-2b83-4ea8-a8ac-7d87634af210)

**Comment by vitsalis** [comment]
Not related to this repository.
